#+TITLE: Future

*
* Applications

** Distributed Models, Pre-training.

Each agent has a local PDG, with all of their local data.

Servies (both public & private) offer a global PDG, on which YOUR pdg executes,
not the other way around. This way you get the things that are the most relevant
to you (your computation drives the process), and there are worries about a
government or private service doing nefarious things with the data. They are
giving you their aggregated dataset + software, but you still own the
processor + the sandbox.

*** Example: Global Health Database
There's a global health database about effects of actions: taking drugs, being
on time, eating chocolate, screens, etc., etc,.

No shady statistics required of the paper; just submit data.
We can therefore use such a tool to increase research reproducibility.
You can also put bounties on specific problems so your research is more in touch
with the desires of people to know things.

You won't waste time reading about studies that have participants whose outcomes
are unlikely to match yours.

*
