#+TITLE:

* General Update
** Behind on Manifolds
** Running election
** Most imoportant problem right now: I cannot follow through on plans
(especially with regard to writing)
I have some weird emotional reaction that derails me even when others put me on track.

* Separating Qualitative and Quantitative PDGs
* The Future of PDGs +
** Try to shift away from optimization
** A visual interface for complex models
** A way of aggregating data
** A model of people
* An IDef Demo
** Connect Tablet to Zoom.
** Do each of the examples in the paper.


* Notes
An argument that would convince me is not tthat
You'd have to convince me that dispate the fact that there are exponentiall y many of the, we can ignore most of them.

Where I'd be interested in going if it turns out to be worthwhile:
want to be convinced that it is worth thinking about these exponentially many terms.


WHat is important? Important for what?
Prove a theorem: you can look at the lower order terms and ignore the rest.

Tell practitioner: these tings are worth learning. Tell the practitioner, who doesn't have a special case PDG, some kind of more complicated thing --- I'm ok with ou assuming it has certain properties,. In this large class of PDGs, the info diagrams give you insight.

Show you you can compute X Y Z, ; come up with a use case.
"Moreover, thinking about the info diagrams gives you more insight into the"
Show it has nice properties.
Need something that's less self referential



** For full paper
Show entropy, etc. do reasonable things.

Suppose we have two spies. One: 50% / 50%. Another says 55% / 45%. You'll get something in between.


** New Paper:
Algorithms.
