#+TITLE:
#+subtitle: a

Probabilistic Dependency Graphs:
A powerful and intuitive modeling language
featuring /Inconsistency/ as your loss function,
simple visual proofs of not-so-simple inequalities,
and





* META
** Gloomy Predictions of How it will go
and how perhaps to mitigate them

*** [#A] Not Enough Time
It is overwhelming likely that I run out of time. After all, I run out of time in every presentation ever, and seldom do people fully understand what I'm saying. I am likely to be more nervous than them and speak faster. Can you imagine that not happening when I'm presenting all of my research of the last three years?

So, given that I know this is going to be a problem, how shall I mitigate it?

*** [#A] Rushed Explanations That Don't Make Sense
Who is going to understand all of the information theory, category theory, thermodynamics, and decision theory that I have to talk about, out of the gate? Nobody.


*** Lack of Practice
*** Delivering it with little sleep
This, I have control over. I will sleep the two nights beforehand, no matter what.
** Morals + Takeaways
***
*** Info + Category Theory
*** ~--- probably not ---~
*** Interfaces are important; this one
** TITLES
*** Probabilistic Dependency Graphs and Inconsistency:
**** Semantics for intuitive diagrams you already use, and the graphical model behind your loss function.

*** Probabilistic Dependency Graphs and Inconsistency:
**** How to model,  measure, and mitigate internal conflict
***** (instead of building systems without internal conflict)
***** (and the benefits of doing so)
**** ((Why inconsistency is more valuable than you think))
**** How to model, measure, and

*** How to Talk about Probabilistic Inconsistency, and why you might want to
**** Epistemic humility for synthetic agents
*** The things you sacrifice by
* CONTENT
** Multiple Title Slides
** Motivation
*** Inconsistency.
Why risk being wrong?
    > Because you could instead be right
    > because you
