
** Summary.

There are concepts / variables, and impact edges, representing belief state. By yoneda / vNM / savage, we can represent values as belief edges to a ``goodness'' domain. 

** 
---

Assuming every domain has a utility (as a special case of a value), the goal is to get a picture of utility revision.

There's a clear notion of binary consistency: we have value-consistency if it's possible to assign a joint value which marginalizes out to all of the value marginals in the picture. However, marginalization out in the case of a general value may not be well defined. For utility, marginalization by probabilities makes sense, as for any other R-convex value (e.g. pref matrices). Otherwise we have to make choices: right or left adjoints (forall vs exists) to the diagonal functor. Non-categorically: have to chose precision or recall


-----

Habits: you've made plans before, and now some of your value has blead into the domain associated with the habit. It's not like the value of the old thing has changed (much?) but now there's a new one, and so the liklihood of connecting to it with a new node has decreased. 

** Alternative Bases

*** Nodes: real values, edges: (~causal) correlations.

Example Nodes:
 - Utility
 - Amount of cake
 - Sleepiness
 - Consumption (and other economic primatives...)


[Aside: Can we think of these as factorized matrices? Possibly...]

Make it so that each variable is oriented, i.e., has a "good" end. This can be done in a dumb way by adding a new variable that is the inverse of the old one. Utility is now a probability distribution over concepts, on a meta level. Updates come from re-weightings, when attention is spent on nodes, utility seeps out of other nodes and into this one.


** ON Categories.

Functorialiy is the right way to think of things in the ideal case, but we can't apply any categoryt theory if an agent is not rational. Properties may  not be preserved, transitivity might not hold, etc. However, if we assume local rationality: that your preferences for these individual domains are conserved --- then we can get some categorical structure and higher order messiness. This is fine, and we'll have to do constructions like homotopy limits/colimits and fibrant/cofibrant replacmenet to get nice things to work out.


** How do preferences change?

Suppose we already have our metric of preference inconsistency. Do we just do graident descent along it? Maybe along subsets of the paramters? 


*** Minimize Inconsistency Locally.
Make it an alternating optimization algorithm? This makes some sense, as we can only see things locally, and doesn't converege (which is also true of humans). Also it requires local identification of the inconsistency.

But why even bother with doing this in the first place? What's so special about inconsistency? What about the entropy term I wanted earlier? 

One possible response to this is to simply write down a prescription for how to update beleifs, like conditioning. But this is just an axiom, and easy to reject. Another approach is to take data from the world, but good empiricism is impossible and data is messy and this is something that wouldn't be easy to get clean measurements for. I want instead to provide a mechanistic, multi-level explanation that provides clean math and then matches data. Which means I need an answer to the question "why do anything when you're inconsistent", and "how do you know you're inconsistent"


**** How do you know you're inconsistent?

**** Why do anything when you're inconsistent?


*** Conscious Choice, Actions invovle belief changes.
Perhaps we can even think of the possible steps from the perspective of utility. If I change my belief or preference here, will my utility go up or down? 

Example where it goes up: 
 - believe that 1 + 1 = 3. Action impacting belief 




*** TODO 


** Voting

Possible 

* Implementation

** Domains

Domains have elements. They don't necessarily have values. In fact we might not need values on most things; the yoneda lema says we can embed values perfectly as links in a cannoncial way. Also, not all domains have values.


---

In a very real sense, it's their space. I've also enjoyed the extra room in summer, but we're not paying to be here and without undergrads it wouldn't exist. Those I've talked to are understandably even more unhappy about the space constraints, given that often even those who have a good reason to be in this building don't have a place to sit and work.
