#+TITLE: Brainstorming


* AN UPDATE RULE
* Trust in One Another
Beta between elements?
What we've been calling \beta is the trust the modeler (\mu) has in each of the cpds.

** Information Flow via Trust
A uses the information from B if A trusts B.

Not using the information:
  A.in, others -> A.out;

Using the information: A.in += B.out.

* THERMODYNAMICS
Beta as a generalized force.


* Observation

Looking Backwards, you want to be accurate
Looking Forwards, it's sometimes useful to be...

 - wishful (you have a guardian angel or only care about high utility events (most events are near zero) )
        >---> surprise good
 - fearful (you have a curse or mostly care about highly unpleasant events (most events again are near zero) )
        >---> surprise bad 
 
Taking different views fr



* VIEWPOINT CALCULUS
Extreme viewpoints = "pure states" = vertices
 
 *  < S C R A T C H >


CONFIDE-ance is the noun form of a transitive verb: to confide.  It is a relationship between two entities. 
And yet, when we think of it as a number, it means certainty, i.e., as in one concept.  
((Certainty is a special, and particularly useful case, of confidence.  But other kinds of confidence are also useful))


* LEARNING THE SAME THING TWICE

Is hearing the same thing twice ever valuable? Doesn't it help you learn to hear the same thing over and over again? Spaced Reputation definitely helps human learning, emperically.  Look at language learning. Stats. 
 
 Variable Confidence means there's some meaningful notion of "degree of learned-ness". For example, 
 
 But what is it that you get when you learn the same thing  more than once? You get two different pathways to that thing. The "PDG Collider",  Two different access paths. This creates a directed cycle, and redundancy in access paths. 
 
It also leads to a potential for homotopy or inhomotopy.


It can be problematic to navigate it when there are too many such cycles. 
The Interface between the two is usually the weakest . 
 

* EXAMPLES


* POTENTIAL TASKS

** Hamilton's Equations
Differentiate Potential with respect to coordinates, and with respect to \beta (momenta/forces?).
See if Hamilton's Equations hold
